version: 0.0
os: linux

# files:
#   - source: /
#     destination: /home/ec2-user/java
files:
  - source: "./target"
    destination: "/home/ec2-user/java"

permissions:
  - object: /home/ec2-user/java
    pattern: '**'
    owner: root
    group: root

hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 100
      #runas: ec2-user
  BeforeInstall:
   - location: scripts/server_clear.sh
      timeout: 100
      #runas: ec2-user
  AfterInstall:
    - location: scripts/privileges.sh
      timeout: 100
      #runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 100
      #runas: ec2-user

