version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/java

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/privileges.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/server_start.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/server_stop.sh
      timeout: 300
      runas: ec2-user
