version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Installing Maven"
      - sudo yum update -y
      - sudo yum install -y maven
  build:
    commands:
      - echo "Building the Java application"
      - mvn clean install
  post_build:
    commands:
      - echo "Rename jar file"
      - mv target/*.jar app.jar
artifacts:
  files:
    - app.jar
    - 'scripts/*.sh'
    - appspec.yml