version: 0.2
phases:
  install:
    runtime-versions:
      java: 11

  build:
    commands:
      - cd EC2-spring-boot-CodeDeploy
      - echo "EC2-spring-boot-CodeDeploy"
      - mvn clean install
